### ISSUE TITLE
Updates to website prior to sharing at OSCon conference July 15

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/roadmap#1]
The OSCon Conference is one of the largest open source projects and IBM is a sponsor at this conference. Kabanero may be shared at the conference.
This is a general item to act as a parent for specific update tasks.

The nature of updates will be dependent on whether code exists or not.

If code exists, Getting started guides are needed for the application stacks that are supported.

Even without code the following updates are needed:

More explanation of the Kabanero Architecture
Development Tool support
Documentation on Jane, Todd, and Champ personas
Why was CodeWind selected for Kabanero?
Why was Tekton selected for Kabanero?
Why was Appsody selected for Kabanero?
Why was Razee selected for Kabanero?
Why was was Prometheus selected for Kabanero?

**Comment by stephenkinder** [comment]
We delivered the work we wanted to deliver for OSCON.
