### ISSUE TITLE
Base Kabanero Operator - Initial Delivery

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/roadmap#10]
Deliver the base code for the Kabanero operator that is capable of installing itself into the OKD 3.11.0 + OLM Kubernetes cluster in a new repository `kabanero-operator.`. The base operator capability includes installing the Tekton operator.

Deliver unit test suites for the Kabanero operator in the same repository.

Document the build instructions in the repository `readme.md` file.

**Comment by marikaj123** [comment]
Kyle will be closing the issue
