### ISSUE TITLE
Website and documentation update for OCP 4.2.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/roadmap#101]
Kabanero-io needs update pre-requisites for Kabanero 0.3.0; updating for OCP 4.2, and temporarily stopping work on OKD until OKD 4.x is GA.

**Comment by mingcyu** [comment]
Will need to cover prerequisites updates
Will need to cover that there is NO upgrade path
Will be spread across many places so need to open several issues

**Comment by marikaj123** [comment]
@mingcyu and @alohr51 - Is the work for the issue on track to complete by Nov-15?

**Comment by alohr51** [comment]
The install doc was updated for 0.3.0 install in this PR. https://github.com/kabanero-io/docs/pull/178/files maybe could use a blurb on why ocp 4.2 now instead of okd. But otherwise I think this issue can close

**Comment by jantley-ibm** [comment]
@alohr I updated the install doc with an OCP vs. OKD blurb and made other minor edits, the PR has you and @stephenkinder as reviewers.  Let me know if it needs changes.

**Comment by marikaj123** [comment]
The work is done and getting ready for publishing.
@stevekinder-ibm - the PR was merged in Master and ready to be published.

**Comment by jantley-ibm** [comment]
closing
