### ISSUE TITLE
Integrate CodeReady Workspaces

### ISSUE THREAD

**Issue by rtaniwa** [kabanero-io/roadmap#127]
Dev contact: john.j.collier@ibm.com

We have decided to deliver CodeReady Workspaces via Kabanero directly, replacing Che, so opening this requirement to track the work required. 

1. Subscribe to the CodeReady Workspaces operator and install it.

2. Once the CRW operator is installed, create the CheCluster resource
      Set openShiftoAuth to false if you haven't set up an auth provider on the cluster yet. Set `tlsSupport` to true to enable HTTPS, and `selfSignedCert` to true if using a self-signed certificate.
      
      If installing Codewind alongside Codeready, use this yaml:
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: codeready-workspaces
spec:
  server:
    cheImageTag: ''
    cheFlavor: codeready
    devfileRegistryImage: 'kabanero/che-devfile-registry:0.7.0'
    pluginRegistryImage: ''
    tlsSupport: false
    selfSignedCert: false
    cheWorkspaceClusterRole: 'eclipse-codewind'
    customCheProperties:
      CHE_INFRA_KUBERNETES_WORKSPACE__START__TIMEOUT__MIN: "5"
      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "0"
      CHE_WORKSPACE_PLUGIN__BROKER_WAIT__TIMEOUT__MIN: "15"
  database:
    externalDb: false
    chePostgresHostName: ''
    chePostgresPort: ''
    chePostgresUser: ''
    chePostgresPassword: ''
    chePostgresDb: ''
  auth:
    openShiftoAuth: false
    identityProviderImage: ''
    externalIdentityProvider: false
    identityProviderURL: ''
    identityProviderRealm: ''
    identityProviderClientId: ''
  storage:
    pvcStrategy: per-workspace
    pvcClaimSize: 1Gi
    preCreateSubPaths: true

3. CodeReady should install and come up. You should be able to access the CodeReady Workspaces URL and 
Red Hat SSO Admin Console URL. 

Setting up Codewind
Codewind currently needs to run as root and privileged, as a result of its dependency on "buildah". Run the following commands to enable that:
- oc adm policy add-scc-to-user anyuid system:serviceaccounts:<namespace>:che-workspace
- oc adm policy add-scc-to-user privileged system:serviceaccounts:<namespace>:che-workspace

Details in https://ibm.box.com/s/pnmbco5dj0mhfw5rdn0g0rkz41tbs454

**Comment by kaczyns** [comment]
Most of the work for this will be in the operator.  There will be hits to the documentation.  The website does not seem to mention Che specifically (only as an option for an IDE) so I don't think there will be a website hit.

**Comment by marikaj123** [comment]
John C. is working on the documenation. The main work is done.
