### ISSUE TITLE
Updating `Getting Started with Codewind and Kabanero` Guide

### ISSUE THREAD

**Issue by j-c-berger** [kabanero-io/roadmap#130]
In lieu of recent changes, the following guide needs to be updated: https://kabanero.io/guides/guide-codewind/

**Comment by marikaj123** [comment]
According to Jake, it will have it complete by tomorrow. Then it will ne ready to be published

**Comment by scottkurz** [comment]
@marikaj123 , @j-c-berger  .. we need to switch over to the java-openliberty stack as soon as we can for articles like this.    How should we track and get this into our plans?

**Comment by j-c-berger** [comment]
@scottkurz, do you mean using `java-openliberty` instead of `application stacks` and `Appsody templates`? 

If so, are these changes as simple as replacing all references of `stacks and applications` to `java-openliberty`? 

Also, why must this change be made? As of now, users can develop Microservices with Codewind without java-openliberty stacks.

**Comment by scottkurz** [comment]
@j-c-berger ..no, the generic references are fine... I only meant to replace specific references to the java-microprofile stack as an example to use the java-openliberty stack instead.

E.g.:
> Under Template, select Appsody Eclipse MicroProfile template. 

The stack has some real perf. issues right off the bat so it's a bad one to give a user a first look...the java-openliberty stack is much better.    

 What repo should I open an issue on then?

**Comment by mingcyu** [comment]
@scottkurz Please create an issue in the codewind guide repository and tag with documentation-id label

**Comment by j-c-berger** [comment]
@scottkurz, please assign me the new issue once you made it. Also, I can begin work on these changes this week and ought to have them done by the end of the this week (Feb. 28th). Thanks and reach out if you wanted to talk more about the guide.
