### ISSUE TITLE
Include Appsody Operator 0.4.0 into Kabanero release

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/roadmap#135]
Develop and certify Appsody Operator 0.4.0
Kabanero may need t include it into its release

Work is done in Appsody.

**Comment by kaczyns** [comment]
@marikaj123 I'm not sure why I'm assigned to this epic. Most of the work will be for other teams. Kabanero pulling in the certified operator is a relatively small change that can be done at any time.
