### ISSUE TITLE
Develop and certify Open Liberty Operator 0.4.0

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/roadmap#136]
Develop and certify Open Liberty Operator 0.4.0
Work is done in Appsody
May need to include the Open Liberty Operator 0.4.0 in Kabanero as a dependency

**Comment by kaczyns** [comment]
@marikaj123 I'm not sure why I'm assigned to this epic.  Most of the work will be for other teams.  Kabanero pulling in the certified operator is a relatively small change that can be done at any time.

**Comment by marikaj123** [comment]
Closing this as the work is done in Apssody
