### ISSUE TITLE
Define the deprecation policy for Kabanero

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/roadmap#145]
Define the deprecation policy for Kabanero

**Comment by marikaj123** [comment]
There needs to be a clear policy on the steps to deprecate a capability in Kabanero to include:

- How to request something be deprecated
- What the review & vetting process is
- How show that something as deprecated
- Identifying the time line for something to be deprecated before being removed

As part of a request to deprecate something, associated impacts must be identified:

- documentation
- test cases
- builds
- source

**Comment by marikaj123** [comment]
Lis of Issues to provide the work:
https://github.com/appsody/stacks/issues/751

**Comment by marikaj123** [comment]
Hi @stevekinder-ibm - Any other child issues need to exist beside the Appsody one listed above? Any child issues needed from the Kabanero StackHub team (@groeges and @kilnerm).  As well, do we need to open a doc issue for ID team (@jantley-ibm)?

**Comment by stephenkinder** [comment]
We can close this epic, the design was completed and the work was accomplished via several issues not organized the epic. In the interest of time, we'll just clean up this dangling paperwork.
