### ISSUE TITLE
ServiceMesh - 1.0.8

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/roadmap#146]
FInd out if we need to move to a new version of ServiceMesh

**Comment by marikaj123** [comment]
@kaczyns - Are we staying with version 1.0.8 rather than moving up?

**Comment by erpenbach** [comment]
Wouldn't we pick up the version of ServiceMesh automatically from OCP?

**Comment by marikaj123** [comment]
@garypicher - Do we need to move a new level for Kabanero 0.9.0?

**Comment by garypicher** [comment]
@marikaj123 No, because we obtain this from the RedHat catalog and rely on them to keep current with patch versions.  We no longer need to track service mesh.
