### ISSUE TITLE
Container Registry Digest/Tag Governance - Champ/Todd tools (Phase 1)

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/roadmap#148]
Container Registry Digest/Tag Governance - Champ/Todd tools

Spec / design for registry digest and tag governance is here: https://github.com/kabanero-io/kabanero-foundation/blob/master/design/digest.md

One of the key concepts of Kabanero is to help teams come together to ensure that what is intended to be used for building applications is being used. Applications and Application Stacks are designed to count on and leverage semver.org versions. While the semver concept is great for understanding the meaning of tags as they are used throughout the lifecycle of applications and their base application stacks, semver itself, does not define any best practices for tagging containers in a container registry. By design, container registries allow the same instance of a container (identified by a digest/sha256) can be labeled with one to many tags values. While the container identifier (digest) is immuteable, the specific tags associated with that instance of the container can change over time.

There are implications of the procedure Champ manages building and publishes application stacks for usage in Kabanero and the enterprise's container tagging strategy. 
Kabanero has several lifecycle validation detection points (build, deploy) where we detect the active stacks and stack versions.  We'd like to alert Champ/Todd to unexpected digest mismatches (variance from best practices) and allow the enterprise to define policy -- e.g. fail the pipeline when the specific digest is not active.

Note: Due the global event, the velocity of the team was such that we could not complete all of the scheduled work related to this epic.  We did complete some significant features however, and we decided to split the work into a Phase 1 and Phase 2 epic (https://github.com/kabanero-io/roadmap/issues/152).   Unfinished work from this (now Phase 1 epic) will be moved to the Phase 2 epic and we will attempt to deliver in the 0.9 milestone.

**Comment by tseelbach** [comment]
overview doc https://github.com/kabanero-io/docs/pull/366/files#

**Comment by tseelbach** [comment]
The above pr (366) uses parts of the design :   https://github.com/kabanero-io/kabanero-foundation/blob/master/design/digest.md

**Comment by marikaj123** [comment]
The rest of the work is completed in the equivalent Epic for Phase 2.
