### ISSUE TITLE
Move up to Tekton pipeline beta version 0.11.0 when available from RH operator

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/roadmap#149]
Tekton Beta pipelines release (0.11.x or 1.0.x) will be available soon. Move up to this release when available from openshift-pipelines-operator, likely timing will target Kabanero 0.9 and ICPA 4.2. Will include Tekton Triggers 0.4.x (in support of beta) and Tekton Dashboard and Webhook extensions 0.6.x (in support of beta). This feature (Epic) would involve multiple child issues:

   1-  take up openshift-pipelines-operator (v0.11.x or 1.0.x, tekton beta version)
    2- update kabanero operator to install dashboard and webhook extension (0.6.x) in support of beta
    3- Kabanero pipelines updated to use the tetkon pipeline beta version.  

Aniticpate that most of the effort will effort will be minor updates and mainly testing,

**Comment by marikaj123** [comment]
After deciding of the release delivery for this Epic then we will create the following child issuues will be created:
    1- take up openshift-pipelines-operator (v0.11.x or 1.0.x, tekton beta version)
    2- update kabanero operator to install dashboard and webhook extension (0.6.x) in support of beta
    3- Kabanero pipelines updated to use the tetkon pipeline beta version.

**Comment by anneqm** [comment]
To keep everyone informed, the Tektoncd/pipelines v0.11.0-rc4 was released today. Please see the https://github.com/tektoncd/pipeline/releases for deprecation and backward incompatibility items.  Note that the openshift-pipelines-operator has v0.11.0-rc2 available, but not yet up to the latest. Expecting tekton pipeline beta released from the tekton community tomorrow. Openshift-pipelines-operator will hopefully be available about a week later, in time for kabanero 0.9.0.

**Comment by anneqm** [comment]
- Tekton Pipelines Beta is released from the Tekton community. https://github.com/tektoncd/pipeline/releases/tag/v0.11.0.  

- In support of beta pipeline, Triggers 0.4.0 and Dashboard & Webhooks Extension 0.6.0 to be released later this week. 

- Expect openshift-pipelines-operator to be made available within a week or so of Triggers release. Will continue to monitor https://quay.io/repository/openshift-pipeline/openshift-pipelines-operator?tab=tags

**Comment by marikaj123** [comment]
Hi @anneqm - Are you aware of any known bug fixes going in the version https://github.com/tektoncd/triggers/releases/tag/v0.4.0 as an ifix that would need to be included in Kabanero 0.9.0?

Any info on the availability release date for the Dashboard release that is expected to be included by Kabanero 0.9.0?

**Comment by marikaj123** [comment]
@anneqm - Any info on when to expect https://github.com/operator-framework/community-operators/tree/master/community-operators/openshift-pipelines-operator  to contain the beta version 0.11.0 for Kabanero 0.9.0 to include?

**Comment by anneqm** [comment]
The beta is now available from the operator community here https://github.com/operator-framework/community-operators/tree/master/community-operators/openshift-pipelines-operator/0.11.0

**Comment by marikaj123** [comment]
Kabanero Epic to include the new Tekton pipeline: https://github.com/kabanero-io/roadmap/issues/149

**Comment by marikaj123** [comment]
Work is done.
