### ISSUE TITLE
Document Kabanero Foundation Instance artifacts.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/roadmap#19]
As part of the enterprise architect's infrastructure-as-code initiatives, the kabanero.io site will document the artifacts which define the Kabanero Foundation Instance. The enterprise architect can then extract the artifacts for a specific Kabanero Foundation Instance and check them into a Github repository. 

Document the artifact list in `kabanero-operator/readme.md` file and how to extract them into files.  Also document the vision: that these artifacts can be modified and stored in Github (Gitops) and applied to the target Kubernetes environment, and the Kabanero operator will instantiate the Kabanero Foundation Instance in the target Kubernetes environment.

**Comment by cajaygle** [comment]
So the idea here is that Github serves as an archive and history of what's been installed?   What seems missing is an enforced linkage between what's in Git and what's been installed -- i.e. how do you know what's in git reflects what's been installed?

**Comment by stephenkinder** [comment]
This is completed in the README.md file of the kabanero-collections repository.  I would expect this to continue to be maintained as the collection evolves.
