### ISSUE TITLE
Document the Tekton Dashboard UI Webhook instructions.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/roadmap#20]
Document the runbook for installing the Github repository webhook, connecting the developer's project to the target Kabanero Instance's configured pipeline for Java-MicroProfile.

**Comment by marikaj123** [comment]
The developer has the required information to be able to deliver by this iteration.

**Comment by Jhschube** [comment]
PR here: https://github.com/kabanero-io/docs/pull/2

**Comment by Jhschube** [comment]
PR merged
