### ISSUE TITLE
Document the initial pre-requisite environment, software and "hardware".

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/roadmap#23]
Document pre-requisites for installing the initial enterprise architect experience.  The initial environment is OKD 3.11.0 + OLM of _some_ predefined size to get through the initial experience.

This initial documentation can be stored in the roadmap `readme.md` file.

**Comment by dacleyra** [comment]
Preliminary documentation is present in fork
https://github.com/dacleyra/roadmap

Includes markdown table generator script that gathers the resource requests and limits from a deployed cluster.

kabanero-operator needs to add Che and Tekton-Dashboard before we have a component complete table

**Comment by stephenkinder** [comment]
I dig the table and documentation. 

- Since this is the general roadmap repository, we have two target environments:  1) The developer's experience and 2) the Kabanero Foundation in a Kubernetes Cluster.  I suggest that we change the title of the section to be clear it is for the latter environment.
- I wonder if it might be easier to manage over time if the table itself was located in a separate markdown file, and referenced from the main `readme.md.`  I could imagine that in the future that release publishing automation would generate this detailed table.

**Comment by dacleyra** [comment]
Additional components to add to sizing:
- openshift-monitoring (prometheus)
- openshift-metering (heapster)
- ~~helm/tiller~~
- kafka eventing 
- olm ui catalog (if not present)

**Comment by stephenkinder** [comment]
This issue was teased apart to allow the initial pre-requisite work to be closed as part of the July 15th initial experience release.  As part of the Kabanero release processing, we need to be able to assess pre-requisite changes from release to release.   As Kabanero becomes more sophisticated, and as new features are added to Kabanero, the pre-requisites need to be included as part of the definition of the work items for those features.

https://github.com/kabanero-io/roadmap/issues/36
