### ISSUE TITLE
Write a guide for codewind

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/roadmap#24]
go here https://microclimate.dev/codewindtechpreview#limitations and install codewind

then create a simple codewind project and write a guide for that (don’t include the installation in the guide) you can write either a Node.js, Spring, and Liberty project with codewind.

For the kabanero.io site this is the first guide so the `/guides` section will need to be redesigned to fit kabanero css.

Also figure out the build process for guides. We need to talk and see if each guide should be a separate repository like OL does.

**Comment by kSee04** [comment]
Closed by https://github.com/kabanero-io/kabanero-website/pull/27
