### ISSUE TITLE
Write the doc for installing codewind

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/roadmap#25]
Right now we can use instructions from https://microclimate.dev/codewindtechpreview#limitations to write our ascii doc for the site.

This is our first doc so the /docs section on the site will need to be redesigned with the kabanero look.

Also figure out how the docs get built in and make sure the deploy will run smooth with the doc.

**Comment by marikaj123** [comment]
Looking for a status update on the percentage of completion. Almost done.

**Comment by kSee04** [comment]
Closed by https://github.com/kabanero-io/kabanero-website/pull/28
