### ISSUE TITLE
Document the contributor license agreement acceptance process

### ISSUE THREAD

**Issue by kyleschlosser** [kabanero-io/roadmap#26]
The requirements and process for accepting the license agreement for contributions needs to be documented.

**Comment by erpenbach** [comment]
Does this issue cover the complete guide for contributoring such as https://github.com/OpenLiberty/open-liberty/blob/integration/CONTRIBUTING.md ?

**Comment by marikaj123** [comment]
Andrew, I guess the work is completed on Kabanero.io, right?

**Comment by marikaj123** [comment]
The work for Kabanero is complete.

**Comment by marikaj123** [comment]
Kabanero link to CLA:  https://github.com/kabanero-io/kabanero-website/blob/master/CONTRIBUTING.md
