### ISSUE TITLE
Add Codewind Che to Kabanero.io website

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/roadmap#3]
We have a repository set up for [Codewind Che](https://github.com/kabanero-io/codewind-che)

We will need a specific build for kabanero.io which will be in the above repository. The build will publish an image to a public registry.

We will also need instructions on how to consume this image either on the kabanero.io site or have the site link to a readme file.

**Comment by alohr51** [comment]
Waiting on the Codewind team to finish their initial kabanero version https://github.com/kabanero-io/codewind-che

**Comment by alohr51** [comment]
this will probably update the work that was done for #24 and #25

**Comment by marikaj123** [comment]
Waiting for  https://github.com/kabanero-io/codewind-che  to be finalized / ready to be promoted- https://github.com/kabanero-io/codewind-che.  Andrew L. is working with Andrew Mak to get an ETA date.

**Comment by marikaj123** [comment]
Waiting for the blocked issue to be resolved by the codewind team: https://github.ibm.com/dev-ex/dev-ex-planning/issues/875.  The team will inform us as to when they can have it resolved by.

**Comment by stephenkinder** [comment]
I'm of the opinion that Che is _*not*_ part of the very first larval delivery.  I'd be ok if we moved this back to the backlog.

**Comment by cajaygle** [comment]
I don't understand what this means with respect to the kabanero.io website.   Is this to include Che as part of the Kabanero Foundation install from Kabanero.io?   Or is this somehow separately making Che available (either hosted or installable) from kabanero.io?

**Comment by deboer-tim** [comment]
It's the prior - allowing the Kabanero operator to include the branded Che in addition to the other bits.

**Comment by stephenkinder** [comment]
I'd like to refine this issue to be just the website advertisement, include Che icons, development experience using remote Che.  The operator itself has implemented the che operator https://github.com/kabanero-io/kabanero-operator/issues/197.    I will add this to this epic:  https://github.com/kabanero-io/kabanero-operator/issues/9.

Please also note the related issue: https://github.com/kabanero-io/kabanero-foundation/issues/83.  I'm thinking that the Kabanero operator will deliver the Che support feature in 0.2.0, but if the appsody extension for Codewind isn't supported in Che, then perhaps we'd defer the advertisement of the support until we can deliver that feature.

**Comment by marikaj123** [comment]
@stevekinder-ibm - Is the work for this issue continue to be targeted for v0.3.0 release?

**Comment by stephenkinder** [comment]
@marikaj123 The project team is looking at ways to contain this work in 0.3.0 of Kabanero.  We should be working on this as if it is going to go -- but be able to pull it back if we cannot contain the feature.

**Comment by alohr51** [comment]
We replaced che with codeready workspaces so closing this issue
