### ISSUE TITLE
Investigate the Eclipse Che Operator

### ISSUE THREAD

**Issue by StringCheeseCR** [kabanero-io/roadmap#31]
Investigate the Eclipse Che Operator and learn how and what it does for use in adding it to the Kabanero Operator in the future.

**Comment by StringCheeseCR** [comment]
Currently waiting on Eclipse to release the RC2 version of the Operator to OperatorHub.io

**Comment by StringCheeseCR** [comment]
Blocked on https://github.com/eclipse/che/issues/11469

**Comment by stephenkinder** [comment]
@StringCheeseCR We reprioritized Che for Kabanero, it will come later.

**Comment by stephenkinder** [comment]
I think we can safely close this issue; since we are actively working on including Che in Kabanero under work items organized under this epic: https://github.com/kabanero-io/kabanero-operator/issues/9.
