### ISSUE TITLE
Develop initial developer's exerience getting started example for Appsody CLI.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/roadmap#32]
Assuming the developer's experience choice is Appsody CLI,  document a simple "Hello World" example showing the Docker-less development experience.

The "Hello World" example demonstrates a simple development iteration and application rebuild. For the plugin experience, add a short typical debug session. For the CLI experience, a simple code modification is made, and Appsody CLI usage is demonstrated.

The initial example is limited to the Java-MicroProfile "stack."

Any exemplary code developed in support of the example is hosted in a kabanero-io repository.

This issue was split out of issue #7 to allow progress independently of Codewind.

**Comment by Jhschube** [comment]
Docs already exist. Opening up issue in the website repo to have the website point to the existing knapp docs.
