### ISSUE TITLE
Create Contribution Guide

### ISSUE THREAD

**Issue by erpenbach** [kabanero-io/roadmap#35]
I assume #26 will go into a Contribution Guide such as https://github.com/OpenLiberty/open-liberty/blob/integration/CONTRIBUTING.md.  Open this item since my question was ignored in #26.

**Comment by marikaj123** [comment]
Kabanero has provided the following guide: https://github.com/kabanero-io/kabanero-website/blob/master/CONTRIBUTING.md.
