### ISSUE TITLE
Document runbook for installing Codewind IDE plugins.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/roadmap#4]
As a developer, I would like to see a list of Kabanero related development tools:

- VS Code
- Eclipse

Document the runbook in markdown format in the readme file for this repository as part of a getting started experience.  Include documentation for any relevant prerequisites.

**Comment by marikaj123** [comment]
According to the issue, 2/3 of the work is blocked as of now.  Waiting on the Codewind team to deliver the feature by probably the week of July 1 or July 8.  As a result, the VS Code and Eclipse part that is blocked.
According to the codewind Epic owner:  The epic for the appsody support in codewind: https://github.ibm.com/dev-ex/dev-ex-planning/issues/852.  The Epic will be released soon after the getting the official Appsody stuff.

**Comment by marikaj123** [comment]
Impact on the July 15 delivery. Needed by July 8.

**Comment by stephenkinder** [comment]
This issue is now partially unblocked since Appsody is available at its open source home. I'm going to refine this issue and separate the Appsody CLI experience from Codewind tasks.

**Comment by deboer-tim** [comment]
Can you clarify what you're blocked on Codewind for? We have working builds of all the bits you can use now and plan to have a milestone release tomorrow. I know we're all waiting on an update to the Che operator and this would block a Kabanero release, but that's not blocking VS Code/Eclipse and you can manually build the Che operator in the meantime.

**Comment by marikaj123** [comment]
Can we please describe to the codewind team the specific functionality we are waiting on?

**Comment by stephenkinder** [comment]
The appsody-enabled plugin has been checked into https://github.com/kabanero-io/appsodyExtension. Hosting the plugin in Kabanero in temporarily necessary because we do not control the project lifecycle hosted at Eclipse -- they have a contribution model that doesn't match the desire for a July 15th initial experience. Longer term, the mainstream Codewind extension will just support Appsody.

**Comment by Jhschube** [comment]
PR for this issue: https://github.com/kabanero-io/docs/pull/3

**Comment by Jhschube** [comment]
So the docs specified at https://github.com/kabanero-io/appsodyExtension work and since they are already documented, the website should point to that readme
