### ISSUE TITLE
Script for Kabanero pre-reqs.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/roadmap#46]
To simplify the initial Kabanero experience for the Operational or Enterprise Engineer, we should provide a script that can install the OKD 3.1.1 prereqs in preparation for the installation of the Kabanero Operator.

I want to keep the pre-requisite install step, and the Kabanero operator installation steps to be separate and discrete for now.  The install experience of the operator will be improved over time, and the operator will manage more and more of the pre-requisites.

This issue includes the improvement to the install instructions.

**Comment by dacleyra** [comment]
Ran into
https://github.com/appsody/tekton-example/issues/16

**Comment by dacleyra** [comment]
PR
https://github.com/kabanero-io/docs/pull/9

**Comment by stephenkinder** [comment]
This issue is blocked pending the resolution of Istio dependencies.
