### ISSUE TITLE
Question: How can I try out Kabanero Foundation ?

### ISSUE THREAD

**Issue by rhuss** [kabanero-io/roadmap#49]
Since on the roadmap there are already very concrete [resource requirements](https://github.com/kabanero-io/roadmap#kabanero-foundation-in-a-kubernetes-cluster-prerequisites) for Kabanero Foundations, I hope there is something to try out. Could you please point me to the place from where I can install Kabanero Foundations as the [repository](https://github.com/kabanero-io/kabanero-foundation) is empty ? Thanks !

**Comment by stephenkinder** [comment]
Hi @rhuss ...  we are revamping the try it page for the Kabanero Instance documentation.  I expect that to get refreshed very shortly, we wanted to provide a partner script that went with the Kabanero operator to help set up some of the security permissions (RBAC) and install some dependent frameworks the operator doesn't handle yet.  

The documentation we are working on is located here: https://github.com/kabanero-io/docs/blob/master/ref/general/kabanero-foundation-setup.adoc .... the script has a PR opened here: https://github.com/kabanero-io/docs/pull/9 ...

Once the PR is merged, we'll simplify the documentation and refresh the website.

**Comment by stephenkinder** [comment]
@rhuss the website was just refreshed for this past iteration.  The try-it experiences are updated.   Hopefully, we start to answer some of your questions on the website.  I'm going to close this issue.  Please feel free to reopen if your specific question remains unanswered and also feel free to continue to open issues with specific questions/concerns.
