### ISSUE TITLE
Enable the download of the Codewind tools for "Appsody" from the Kabanero Site.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/roadmap#5]
Because of the uncertainty of availability of Codewind tools for "Appsody" at the Eclipse and VSCode marketplaces, the kabanero.io site will offer a download of either plugin.

Note: This tactical approach will support only mac-os for the time being.

**Comment by marikaj123** [comment]
Can we please describe to the codewind team the specific functionality we are waiting on?

**Comment by stephenkinder** [comment]
The appsody-enabled plugin has been checked into https://github.com/kabanero-io/appsodyExtension. Hosting the plugin in Kabanero in temporarily necessary because we do not control the project lifecycle hosted at Eclipse -- they have a contribution model that doesn't match the desire for a July 15th initial experience. Longer term, the mainstream Codewind extension will just support Appsody.

**Comment by stephenkinder** [comment]
This issue is no longer necessary since Codewind is available externally.
