### ISSUE TITLE
Move the pre-req documentation from roadmap to the kabanero-foundation

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/roadmap#51]
Now that we have a repository for the Kabanero foundation, we should move the pre-requisite documentation to that repository's README.md.

We need to also make sure that any links to the pre-requisites in the Kabanero documentation and website are also updated.

**Comment by Jhschube** [comment]
The docs have been moved over to the foundation repo. Have a PR to remove the foundation stuff from the Roadmap repo. https://github.com/kabanero-io/roadmap/pull/56

**Comment by marikaj123** [comment]
@jhschube - Who needs to take the next action before the issue can get closed?

**Comment by marikaj123** [comment]
@stephenkinder - Can the issue get closed.
