### ISSUE TITLE
Process for handling the signed CLA documents in Kabanero community

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/roadmap#55]
https://github.com/kabanero-io/kabanero-website/blob/master/CONTRIBUTING.md
1- where do the Kabanero team store the signed documents? 
2- Is there an expiry date for the signed document?
3- How do the documents are processed (ie: how to avoid the same person from keeping signing the CLA (IBM or others).

**Comment by alohr51** [comment]
Some information:

1. The website has a [page on how to contribute](https://kabanero.io/contribute/)
   1. The website links to our [CONTRIBUTING.md readme ](https://github.com/kabanero-io/kabanero-website/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md readme explains the CLA and the CLA itself tells people to email it to cla@kabanero.io

The email is accessible through our domain host gandi.net. **A limitation is that email box will only store 3GB of email.**

This is just how it is today. A better process would be nice.

**Comment by marikaj123** [comment]
Converted the issue into an Epic as per Steve's suggestion.

**Comment by alohr51** [comment]
https://cla-assistant.io/ requires a GitHub gist to contain the CLA - this gist can only exist under a GitHub user account so the plan is to create a functional GitHub User to hold the CLA. Alan is setting that up currently.

We can then enable cla assistant for the entire Kabanero-io GitHub org so all PR's from all repositories in our org are automatically enrolled in this CLA check.

Harry from the OL team noticed some interesting tidbits from the [legal TOS/privacy policy of the CLA assistant service](https://gist.github.com/CLAassistant/3a73e4cd729c9d0a6e30) about PII.

Another option would be to setup our own CLA assistant service with our own database so we store all the info and not cla assistant.

**Comment by alohr51** [comment]
Also found the same team created a [CLA assistant GitHub Action](https://github.com/cla-assistant/github-action) which helps with one of the main problems above about where it's storing signatures. This GitHub action will store the signatures directly in the repo instead of some hosted database out of our control.

Only drawback so far is the GitHub action won't work with PR's opened via a fork, which is a main flow for development on GitHub. Its a GitHub specific issue and they said its something they are working on.

**Comment by alohr51** [comment]
[CLA assistant](https://cla-assistant.io/) is now in effect for the entire Kabanero-io GitHub org

What this means is for every Pull Request (PR) in every repository under Kabanero-io this webhook will check if the PR submitter/s have signed our CLA, if they have not, it will fail the status check until they do sign the CLA (the tool provides a link to sign) when they sign it the tool will automatically pass the status check and the PR can then be merged. You only have to sign once for the whole organization. 

any changes to configuration of the assistant would need to go through Alan LIttle. His account is the one configured to use this tool.

The CLA is hosted in a gist under the `kabanerogithub` GitHub account. Andrew Lohr and Alan Little have access to this functional ID
