### ISSUE TITLE
Investigate test framework and automation

### ISSUE THREAD

**Issue by StringCheeseCR** [kabanero-io/roadmap#57]
Determine which test framework should be used for Kabanero

**Comment by StringCheeseCR** [comment]
From a discussion with Kyle
"we should have a vision towards running all of these processes as Tekton pipelines, and the typical pipeline definitions for an operator or a cli project should be available as collections.  Tekton pipelines include the concept of a task which is a command or the like, the tasks get assembled into pipelines, and then you run the pipelines.  Our infrastructure should be built on this concept so if we start from my request to have the operator integration tests run, we need an integration test task, and an initial pipeline that includes something like run the integration tests, and then publish the results back to the PR. And you therefore need to have a Kubernetes cluster available for your test infrastructure as a first step"

**Comment by tseelbach** [comment]
hi @StringCheeseCR Chris, Are you working on this, or should we unassign and put in the backlog?

**Comment by StringCheeseCR** [comment]
@tseelbach I am but if you're looking for a build infrastructure quickly then that should be spun off into a separate task as I've still been looking into both Tekton & GitHub Actions (yes, i know it's in Beta)

**Comment by StringCheeseCR** [comment]
Design document available at: https://ibm.box.com/s/2jo0zd9yb2s5ea169d723ta78rxapl67

**Comment by marikaj123** [comment]
@gecock - Is the work continued into the next release, v3?

**Comment by gecock** [comment]
We've done enough investigation to get started. We will create new issues to track our work moving forward
