### ISSUE TITLE
Jane's Kabanero experience should likely involve pointing the Codewind and Appsody CLI to Kabanero Repo

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/roadmap#61]
@stephenkinder commented on [Mon Aug 19 2019](https://github.com/kabanero-io/kabanero-collection/issues/58)

The current directions on the kabanero.io website do not show how to change the CLI to the default Kabanero Repository.

**Comment by Jhschube** [comment]
Codewind needs to update their VS code extension to 0.3.0 in order for the current release of the appsody-for-codewind extension to work. ~I tried using older (deprecated) versions of the extension but they are failing to build projects as well.~

**Comment by marikaj123** [comment]
Dependency on including the newest version for the base codewind extension v0.3.0.

**Comment by Jhschube** [comment]
docs have now been merged
