### ISSUE TITLE
Create UBI based container to run kubectl commands 

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/roadmap#62]
We could use a container built on top of UBI that supports running kubectl commands.  Currently the pipelines use https://hub.docker.com/r/lachlanevenson/k8s-kubectl and another popular version seems to be https://hub.docker.com/r/bitnami/kubectl/

**Comment by ianpartridge** [comment]
Note that other teams in IBM have already done this:

https://access.redhat.com/containers/?tab=overview#/non_registry/ibm/eventstreams-kubectl-2019-2-1
https://access.redhat.com/containers/?tab=overview#/non_registry/ibm/aios-kubectl

Probably we need to converge on a common one.

**Comment by kvijai82** [comment]
Thanks @ianpartridge.  Good to know they already exist and yeah would be good to have one common one that we can all go with in the future.

**Comment by tseelbach** [comment]
could/should  we add kabanero and oc commands?

**Comment by stephenkinder** [comment]
@tseelbach can you please investigate this for this release?  @garypicher I think we need to clean up usage of these utility containers.

**Comment by kvijai82** [comment]
We have kabanero/validate-collection, which is essentially ubi + kubectl + a script.  We can try to put a version there w/o the script and we would have what we want for this.  Will try to get this in for 0.2.0 but this might slip til next week based on other priorities.

**Comment by kvijai82** [comment]
Published kabanero/kabanero-utils which has kubectl in it.
