### ISSUE TITLE
External dependency on Tekton: Provide documentation on how Jenkins can be used for Build or Deploy steps along with event generation to tell us to move forward.

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/roadmap#66]
To Tekton:

For those customers that have Jenkins as their default devops pipeline, we would like to include them in the collection build and deploy process.  

Provide documentation and a sample that shows how to add a call to Jenkins to either Build a docker container or deploy the docker container.  This would require a method that generates an event that enables the default tekton pipeline / stage to continue.

**Comment by mnuttall** [comment]
The first piece of documentation should describe how to use Jenkins to deploy images previously built by a Kabanero/Tekton pipeline.

**Comment by marikaj123** [comment]
@anneqm - Hi Anne, any update on this issue would be appreciated.

**Comment by anneqm** [comment]
@marikaj123 The team is working on it. To clarify we are only working the scenario using Jenkins for the deploy process, not the build process.

**Comment by marikaj123** [comment]
@anneqm - Any status on the completion date.

**Comment by akihikokuroda** [comment]
Notes of the work

# prereq:
openshift 3.1.1 installed,
kabanero-foundation cloned
appsody installed
kabanero-pipeline cloned

# Build
## Tekton pipeline update
Edit kabanero-pipelines/pipelines/incubator/build-deploy-pipeline.yaml
- Delete deploy step in the pipeline
- Change the pipeline name and `refTask` name

Apply the pipeline yaml to the `kabanero` namespace
```
oc apply -f kabanero-pipelines/pipelines/incubator/build-deploy-pipeline.yaml -n kabanero
```
## Project creation
Create a sample project using appsody

1. appsody init nodejs-express
1. appsody build
1. appsody deploy --generate-only

Push to github `repo1/project1` 

git init, git add, git remote, git commit, git push

## Build with `Tekton`
Edit the `DOCKER_IMAGE` and `APP_REPO` to match the project in kabanero-foundation/scripts/appsody-tekton-example-manual-run.sh and run it.
```
DOCKER_IMAGE="${DOCKER_IMAGE:-docker-registry.default.svc:5000/kabanero/project1}"

APP_REPO="${APP_REPO:-https://github.com/repo1/projet1/}"
```
Note:

  If it fails in check
  - Edit the stack name in .appsody-config.yaml.  "appsody" -> "kabanero"
  - Run the script again

Make sure image is pushed into Openshift image repository (Look at Openshift - kabanero project - build->images)

## Update project
Create a Jenkinfile file in the root directory of the project with the following contents
```
podTemplate(label: 'label', cloud: 'openshift', serviceAccount: 'appsody-sa', containers: [
    containerTemplate(name: 'kubectl', image: 'lachlanevenson/k8s-kubectl', ttyEnabled: true, command: 'cat')
  ]){
    node('label') {
        stage('Deploy') {
            container('kubectl') {
                checkout scm
                sh 'sed -i -e \'s#applicationImage: .*$#applicationImage: docker-registry.default.svc:5000/kabanero/project1#g\' app-deploy.yaml'
                sh 'cat app-deploy.yaml'
                sh 'find . -name app-deploy.yaml -type f|xargs kubectl apply -f'
            }
        }
    }
}
```

Match the "docker-registry.default.svc:5000/kabanero/project1" to the pushed image
Push the Jenkinfile  file to github

# Deploy
## Install / Configure Jenkins
1. Install Jenkins from the Openshift `Service Catalog`
2. login to Jenkins using Openshift credentials
### Configure jenkins
1. select `Multibrach pipeline` in the `New Item`
2. Selet `Add source` - `Github`
3. Add credential
  - github
  - user name
  - access token

 4. Fill in `owner` and `repository`
 5. Save and apply

The Jenkins starts scanning the repository and deploying the project
## verify deployment
Open the application in the browser.
openshift application->routes -> <project>

**Comment by marikaj123** [comment]
@akihikokuroda - Please ensure the format is agreed on by the architects.

**Comment by akihikokuroda** [comment]
@marikaj123 Who is the architect for this matter?  Would you add the architect as the subscriber of this issue?  Thanks!

**Comment by akihikokuroda** [comment]
Where should this documentation be?  In the kabanero.io/docs ? @ralanlittle any suggestions?

**Comment by dewan-ahmed** [comment]
As @mnuttall mentioned above, the first piece of documentation should be how to use Jenkins to deploy images previously built by Tekton. The draft work for this piece is here: https://ibm.box.com/s/8mwhdcof2hq6ptf3na61imrhdhnaeoa2 and being reviewed. Please let @akihikokuroda & me know if the first piece of the documentation is Ok and we can start on the second piece - event generation.

**Comment by akihikokuroda** [comment]
This document has enough information for this issue.  There is no additional piece necessary.

**Comment by dewan-ahmed** [comment]
Thanks @akihikokuroda

**Comment by marikaj123** [comment]
@anneqm - Hi Anne, Is the issue ready to close?

**Comment by anneqm** [comment]
@marikaj123 Hi Monica, the draft is finished and available here: https://ibm.ent.box.com/file/537603281960.   Is there another issue to address publishing it in an appropriate place?

**Comment by akihikokuroda** [comment]
@anneqm, @dewan-ahmed is working on to put the doc in the kabanero.io doc following the guide given by @alohr51

**Comment by akihikokuroda** [comment]
PR in the kabanero-io/docs is here https://github.com/kabanero-io/docs/pull/151.

**Comment by akihikokuroda** [comment]
We are thinking that it may good fit in the guide section in the kabanero.io instead of the doc section.

**Comment by akihikokuroda** [comment]
We are thinking that it may good fit in the guide section in the kabanero.io instead of the doc section.  Does anybody have different opinions? @anneqm @marikaj123 Would you confirm if it's OK?

**Comment by anneqm** [comment]
Guide section makes sense to me. Thanks for checking.

**Comment by anneqm** [comment]
Here's the associated PR for the guide section:  https://github.com/kabanero-io/draft-guide-jenkins-integration-with-kabanero/pull/1

**Comment by marikaj123** [comment]
It is on Alan's list for doc review and testing

**Comment by anneqm** [comment]
@marikaj123, the updated PR for the guide is available for review here: https://github.com/kabanero-io/draft-guide-jenkins-integration-with-kabanero

**Comment by marikaj123** [comment]
@alohr51 - The guide is in draft

**Comment by marikaj123** [comment]
Need reviews with OM

**Comment by anneqm** [comment]
Nate has finished his review and his suggestions were incorporated. 
@ralanlittle would you please review the latest and provide feedback/comments? 
https://github.com/kabanero-io/draft-guide-jenkins-integration-with-kabanero
This guide describes how to built with Tekton and deploy with Jenkins.  A PR was opened by Charlotte Holt and you are assigned as Reviewer. 
https://github.com/kabanero-io/draft-guide-jenkins-integration-with-kabanero/pull/10/files.  
Thanks!

**Comment by anneqm** [comment]
Guide has been published on the Kabanero.io/guides website at this URL: https://kabanero.io/guides/jenkins-integration-with-kabanero/
