### ISSUE TITLE
Technical Foundation - release 0.2.0

### ISSUE THREAD

**Issue by dianak2016** [kabanero-io/roadmap#67]

**Comment by stephenkinder** [comment]
@jantley-ibm please fill in your profile on GitHub so folks can find your name to tag you. 

I've built up the list of 0.2.0 `what's new` that we will publish with the release notes in the kabanero-foundation [here](https://github.com/kabanero-io/kabanero-foundation/releases).

@alohr51 @jantley-ibm I think we need to "advertise" what's new on the website when it drops.  That said, we don't have to do it directly the same day, so for 0.2.0 release, but it should be a common practice?  Do we have a plan for this already, or is this something we need to develop together?

**Comment by alohr51** [comment]
@stephenkinder the [What's New doc](https://github.com/kabanero-io/docs/blob/master/ref/general/whats-new.md) is a markdown file that needs to be updated. Then we can cut 0.2.0 on the docs repo. 

The website will pop that up for new visitors when we enable the feature.

**Comment by marikaj123** [comment]
@alohr51 - Hi Andrew, is it ready to close?

**Comment by alohr51** [comment]
seems like this issue was for all of kabanero to release 0.2.0? I am unsure, maybe @dianak2016 can confirm. If that's the case we would have to make sure everyone released 0.2.0

the docs and landing page are released so that stuff is good.

**Comment by dianak2016** [comment]
Right, this is for release 0.2.0 in general.  Once all the associated tech foundation issues close, this epic can close.  I see that #86 is holding it up, but it was moved to 0.3.0.  Therefore, I'm going to close this epic.
