### ISSUE TITLE
Develop initial developer's exerience getting started example for Codewind.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/roadmap#7]
Assuming the developer's choice of Kabanero Codewind plugin is installed document a simple "Hello World" example showing the Docker-less development experience using Codewind micro-service development using Appsody projects.

The "Hello World" example demonstrates a simple development iteration and application rebuild using the plugins.  For the plugin experience, add a short typical debug session.   
The initial example is limited to the `Java-MicroProfile` stack.

Any exemplary code developed in support of the example is hosted in a `kabanero-io` repository.

**Comment by stephenkinder** [comment]
This issue is now partially unblocked since Appsody is available at its open source home.  I'm going to refine this issue and separate the Appsody CLI experience from Codewind tasks.

**Comment by marikaj123** [comment]
Can we please describe to the codewind team the specific functionality we are waiting on?

**Comment by stephenkinder** [comment]
The appsody-enabled plugin has been checked into https://github.com/kabanero-io/appsodyExtension.  Hosting the plugin in Kabanero in temporarily necessary because we do not control the project lifecycle hosted at Eclipse -- they have a contribution model that doesn't match the desire for a July 15th initial experience.  Longer term, the mainstream Codewind extension will just support Appsody.

**Comment by Jhschube** [comment]
Debugging is not currently supported with the appsody extension for VS code and Eclipse, but I have put together a hello world walkthrough that could probably use some adjustments. https://github.com/kabanero-io/docs/pull/4

**Comment by Jhschube** [comment]
docs were merged
