### ISSUE TITLE
Investigate what are other open source projects using for test automation

### ISSUE THREAD

**Issue by StringCheeseCR** [kabanero-io/roadmap#71]
What are projects like Tekton, Appsody, etc doing when it comes to test automation for their projects?

**Comment by gecock** [comment]
Looks like Tekton has scripting for end to end testing with scripts to set up test clusters on google cloud

https://github.com/tektoncd/pipeline/blob/master/test/e2e-tests.sh
https://github.com/tektoncd/plumbing/blob/master/scripts/e2e-tests.sh

**Comment by gecock** [comment]
Appsody Operator spins up a single server OKD cluster with each build and then runs testing on that env using Travis

Set up cluster -- https://github.com/appsody/appsody-operator/blob/master/Makefile#L23
Unit Test -- https://github.com/appsody/appsody-operator/blob/master/Makefile#L32
E2E Test -- https://github.com/appsody/appsody-operator/blob/master/Makefile#L35
Travis build example -- https://travis-ci.com/appsody/appsody-operator/builds/129496727

**Comment by gecock** [comment]
We've investigated a number of different options for getting automated testing going for Kabanero. This information will prove useful, but we first need to get into the trenches and just start creating automated tests and working with development. Closing this as we've done enough investigation to get started.
