### ISSUE TITLE
Expose kabanero CLI as a first class part of the Kabanero experience

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/roadmap#72]
Expose kabanero CLI as a first class part of the Kabanero experience

documentation and operator updates

**Comment by mtamboli** [comment]
Please provide the scope and high level use cases for this Epic.

**Comment by marikaj123** [comment]
Tom and @davco01a - As being the child issue "kabanero-command-line#3Add results to the examples in the doc, once the results are defined." of this Epic, would it be delivered in release-0.2?
