### ISSUE TITLE
Simplify DevOps webhook and pipeline setup - Phase 0

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/roadmap#75]
The purpose of this work item is to do the following

Accept as input (on the Kabanero operator) 1..n git team organization names. In this organization Jane will create Git repositories which will contain Appsody (future S2I) applications. These organization names will be used by the event discriminator to decide the appropriate pipeline to call, and project (name space) into which to deploy the application, and whether the repo is valid.
a) Champ will set up a simple webhook as part of Kabanero install at the git organization level, by simple, we mean a URL pointing to an initial event handler.
b) Jane can if desired, establish the same URL as a webhook on the other git repositories or her forks of team repositories. This will cause events to flow to the initial event handler, where they will be build and deployed by default into a private project (namespace), if Jane has been defined in the more global git organization.

The Kabanero operator defines the docker repository into which we will store applications that are built based upon the webhook.

The webhook will gather information on the action that was taken by Jane and build an event request (See #4) to topic “Discriminate”.

We will define a simple in-memory queue with well-defined push and pull interfaces that can be replaced later with different queuing mechanisms. But initially it can be just an in-memory queue in the same pod as the webhook.

The consumer for “Discriminate” will take the message and based on the action from git, will push a “Build” or “BuildandRespond” message on to the topics. *** State diagram is needed for git flows supported **

Build consumer will cause a build pipeline to be initiated. The next step will come from a docker repo webhook

BuildandDeploy consumer will cause a build pipeline to initiate, and results gathered must push a “ReportResults” event

Report results responds to git the state of the PR completion.

Docker webhook listener receives docker updates. In the initial listener we will gather the information and push to a “Docker Distriminator”.

Docker Discriminator will drive deploypipeline.

**Comment by ralanlittle** [comment]
The purpose of this work item is to do the following
1) Accept as input (on the Kabanero operator) 1..n git team organization names. In this organization Jane will create Git repositories which will contain Appsody (future S2I) applications. These organization names will be used by the event discriminator to decide the appropriate pipeline to call, and project (name space) into which to deploy the application, and whether the repo is valid.
a) Champ will set up a simple webhook as part of Kabanero install at the git organization level, by simple, we mean a URL pointing to an initial event handler.
b) Jane can if desired, establish the same URL as a webhook on the other git repositories or her forks of team repositories. This will cause events to flow to the initial event handler, where they will be build and deployed by default into a private project (namespace), if Jane has been defined in the more global git organization.

2) The Kabanero operator defines the docker repository into which we will store applications that are built based upon the webhook.

3) The webhook will gather information on the action that was taken by Jane and build an event request (See #4) to topic “Discriminate”.

4) We will define a simple in-memory queue with well-defined push and pull interfaces that can be replaced later with different queuing mechanisms.  But initially it can be just an in-memory queue in the same pod as the webhook.

5) The consumer for “Discriminate” will take the message and based on the action from git, will push a “Build” or “BuildandRespond” message on to the topics.   *** State diagram is needed for git flows supported **

6) Build consumer will cause a build pipeline to be initiated. The next step will come from a docker repo webhook

7) BuildandDeploy consumer will cause a build pipeline to initiate, and results gathered must push a “ReportResults” event 

8) Report results responds to git the state of the PR completion.

9) Docker webhook listener receives docker updates.  In the initial listener we will gather the information and push to a “Docker Distriminator”.

10) Docker Discriminator will drive deploypipeline.

**Comment by marikaj123** [comment]
Looking to have a partial work going into 0.3.0.

**Comment by marikaj123** [comment]
work is complete.
