### ISSUE TITLE
Initial Enterprise Architect Install Experience July 15th

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/roadmap#9]
###  Entry Point
An enterprise architect discovers kabanero.io through social media, organic search or from his colleague after their experience with Issue #2 and wishes to experiment with the Kabanero Foundation components.

### Initial State Assumptions
The enterprise architect has an existing OKD 3.11.0 Kubernetes Cluster that happens to match the documented prerequisites or creates a new environment.  The OKD 3.11.0 environment already has the Operator Lifecycle Manager (OLM) installed, or the enterprise architect installs in preparation for the Kabanero Foundation install.  Documentation indicates the software and hardware requirements.

### Kabanero experience
The subject enterprise architect:

-  reads the "try-it" information for the Kabanero foundation presented at the kabanero.io website and follows the directions:
- downloads the Kabanero Foundation operator and executes the installation runbook.
- runs the operator verification operation to validate all of the Kabanero Foundation components are active and operational.

### Result
- The supplied Kubernetes cluster has Kabanero Foundation installed.
- The following default Kabanero Foundation components are installed:
  * Istio
  * Knative
  * Tekton Operator
  * Tekton Dashboard Extension
  * Kafka Operator
  * Kabanero Tekton Build Pipeline for Java-MicroProfile
  * Che

**Comment by marikaj123** [comment]
According to Steve, the Epic can be closed.
