### ISSUE TITLE
Kabanero-Eventing Phase 0.

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/roadmap#94]
Demonstrate the Kabanero Event Triggers, which will demonstrate driving the Build pipeline for some Github events, and Deploy pipelines for others.

1) Define trigger metadata schema
1) Define collection metadata schema for triggers, allowing for triggers that apply to the Kabanero Instance (all collections) and triggers that are overridden for a specific collection.
1) Define webhook -- manually.
1) Trigger that demonstrates a single repository able to build and deploy based on discrete Github events.
1) Kabanero operator installed.
1) Deliver Phase 0 collection release using triggers -- `0.3.0triggers` with the idea that it will become the default collection in a subsequent release of Kabanero.

**Comment by mchenggit** [comment]
Removed label "documentation" as Phase 0 is still experimental, and will not be formally documented. Informal documentation is provided via README.md.

**Comment by marikaj123** [comment]
work is complete
