### ISSUE TITLE
Update Foundation Readme with OCP/OKD 4.x discussion.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/roadmap#95]
Document why Kabanero is jumping to the commercial version of OpenShift while waiting for OKD Open Project to become available.

**Comment by marikaj123** [comment]
@stevekinder-ibm and @jantley-ibm - Do we need ID to review the readme content?

**Comment by stephenkinder** [comment]
@marikaj123 @jantley-ibm So there a number of documentation efforts related to our upgrade of infrastructure pre-requisites.  The rationale for Kabanero moving to a commercial release needs to be explained.  For commercial products that might base on Kabanero, likely need to explain the upgrade process -- i.e. manually move from the 3.11 environment to the 4.2 environment.
