### ISSUE TITLE
Dependency:  Tekton Dashboard and Extension which supports Tekton 0.7 & Knative 0.8 & ServiceMesh

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/roadmap#96]
This issue tracks the dependency on the ancillary projects of Tekton (Dashboard and Webhook Extension) to support the desired release of RH supplied Tekton 0.7, Knative 0.7 and the built-in delivered RH ServiceMesh skinned Istio component.

**Comment by anneqm** [comment]
@stephenkinder,  Tekton Dashboard and Extension will be knative 0.8, not knative 0.7, please advise if you can update the issue description to show knative 0.8 instead of 0.7?

**Comment by anneqm** [comment]
Tekton Dashboard with Webhooks Extension release 0.2.1 will address this dependency. It should be available soon.

**Comment by anneqm** [comment]
An updated Tekton dashboard and webhooks extension, v0.2.1 is now available from https://github.com/tektoncd/dashboard/releases/tag/v0.2.1. Please see https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/InstallOnOpenshift.md for instructions on bringing this up on: 

- OpenShift 4.2
- Istio via ServiceMesh 1.0.1 operator
- Tekton 0.7 via Pipelines 0.7 operator
- Knative Eventing via 0.8 operator
- Knative Eventing Contrib 0.8 installed directly
- Knative Serving from the 1.1.0 Serverless Operator
