### ISSUE TITLE
Kabanero Che hosted on OCP 4.2.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/roadmap#98]
The Kabanero Che container needs to run on OCP 4.2.

**Comment by marikaj123** [comment]
@stevekinder-ibm - Has the issue been tested or do we need to find someone to test this issue?

**Comment by marikaj123** [comment]
Andrew Mak is documenting the steps while he is testing it.

**Comment by makandre** [comment]
I thought this was being handled in https://github.com/kabanero-io/docs/issues/118?

**Comment by dianak2016** [comment]
@makandre, yes let's keep tracking the documentation in 118.

**Comment by makandre** [comment]
Codewind `0.6.0` will run on OCP 4.2.  It requires `Che 7.3.1`; Kabanero-che was rebuilt based on `7.3.1` and released as https://github.com/kabanero-io/kabanero-che/releases/tag/0.6.0

**Comment by marikaj123** [comment]
@stephenkinder - Documentation is tracked by kabanero-io/docs#118. Is there more work needed by this issue or is the work complete?

**Comment by marikaj123** [comment]
Operator to pull a container of CHE 7.3.1 with codewind 0.6.0
